// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db_queries

import (
	"time"

	"github.com/google/uuid"
)

type ReferralCode struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Code      string     `json:"code"`
	ExpiredAt time.Time  `json:"expired_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type Session struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	RefreshToken string     `json:"refresh_token"`
	ExpiredAt    time.Time  `json:"expired_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
}

type User struct {
	ID           uuid.UUID  `json:"id"`
	Username     string     `json:"username"`
	ReferrerID   *uuid.UUID `json:"referrer_id"`
	HashPassword string     `json:"hash_password"`
	DeletedAt    *time.Time `json:"deleted_at"`
}
