// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db_queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CreateReferralCode(ctx context.Context, arg CreateReferralCodeParams) (CreateReferralCodeRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteReferralCodeByUserID(ctx context.Context) (*time.Time, error)
	DeleteSessionByUserID(ctx context.Context, userID uuid.UUID) (*time.Time, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (*time.Time, error)
	// queries.sql
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
